databases:
  - name: newline-blog-db
    databaseName: newline_blog_db
    user: newline
    plan: free

services:
  - type: redis
    name: sidekiq-redis
    region: ohio
    ipAllowList: [] # only allow internal connections
    plan: free
    maxmemoryPolicy: noeviction
  
  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newline-blog-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: newline-blog
    runtime: ruby
    region: ohio
    buildCommand: './bin/render-build.sh'
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newline-blog-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false